// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciodevoPNXEshFbq0G98Mw2ryG5Hjk0c',
    appId: '1:823330386549:android:eeeeea5fdaea66a69c7e3c',
    messagingSenderId: '823330386549',
    projectId: 'smartbin-2ab4f',
    databaseURL: 'https://smartbin-2ab4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-2ab4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJ9eSi7PnTtou__N_sZadtD7P7fb9G3o',
    appId: '1:823330386549:ios:10e55d77b4beb6e19c7e3c',
    messagingSenderId: '823330386549',
    projectId: 'smartbin-2ab4f',
    databaseURL: 'https://smartbin-2ab4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-2ab4f.appspot.com',
    androidClientId: '823330386549-hotuieru99lb9or9cirnaiivdnvdb7l2.apps.googleusercontent.com',
    iosClientId: '823330386549-k5t71b6ubuae7208pev08jpbm6suo2kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
